### ISSUE TITLE
[Crash] Startup Crash

### ISSUE THREAD

**Issue by Hydraheads** [SuperMartijn642/SuperMartijn642sCoreLib#10]
**Version Info**
- Minecraft, 1.12.2
- Core Lib, 1.0.16a (and any version after the 1.0.14 build)

**Steps to Reproduce**
In my modpack, updating past the Nov. build causes a crash on startup. I am unable to get Tesseract updates as a result. The modpack is Jojovein. Sorry for mistaking it for something else earlier.

**Crash report (~/logs/latest.log)**
[2022-04-12-3.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/8483426/2022-04-12-3.log)

**Comment by SuperMartijn642** [comment]
I believe someone had issues before when using VanillaFix, but I don't remember if it was for 1.12. Could you see if the game loads correctly with VanillaFix disabled?

**Comment by SuperMartijn642** [comment]
Closing due to no response
