### ISSUE TITLE
[Crash] 1.12.2 crash with the latest version

### ISSUE THREAD

**Issue by Cheremenin** [SuperMartijn642/SuperMartijn642sCoreLib#13]
**Version Info**
- Minecraft, 1.12.2
- Core Lib, 1.1.0

**Steps to Reproduce**
Crashing upon launch after updating to the new versions of your mods from 2023
Reverting back to the last versions from 2022 and it works fine.

**Crash report (~/logs/latest.log)**

[crash-2023-01-03_18.39.03-client.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10337989/crash-2023-01-03_18.39.03-client.txt)

**Comment by SuperMartijn642** [comment]
Please update Connected Glass to version 1.1.6.
