### ISSUE TITLE
[Bug] Can't join discord

### ISSUE THREAD

**Issue by JLSkyzer** [SuperMartijn642/SuperMartijn642sCoreLib#15]
![image](https://user-images.githubusercontent.com/60830349/211168226-c3b19098-cd00-4a50-b5bb-53bdb1b98add.png)
Why, i can't join the discord ? can you check if i'm ban ?
Monkey.D.JLSkyzer#3951
909862540945793094

**Comment by SuperMartijn642** [comment]
The account name and user id you mention are not banned from the server (or have even been in the server).
There is an account with the name 'JLSkyzer' who was kicked by CiFru_ and then banned by me over a year ago, however that account now appears to be deleted.
