### ISSUE TITLE
[Crash] Crash happens when starting game.

### ISSUE THREAD

**Issue by YiRanMushroom** [SuperMartijn642/SuperMartijn642sCoreLib#19]
**Version Info**
- Minecraft, 1.12.2 
- Forge, 14.23.5.2860
- Core Lib, 1.1.2

**Steps to Reproduce**
N/A

**Crash report (~/logs/latest.log)**
[crash-2023-02-12_23.15.31-client.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10716371/crash-2023-02-12_23.15.31-client.txt)

**Comment by SuperMartijn642** [comment]
My core library loads fine without anything else installed.
Could you narrow down which other mods are needed to reproduce the issue?

**Comment by YiRanMushroom** [comment]
I am finding but it seems really hard

**Comment by YiRanMushroom** [comment]
Basically I am forking E2E, but I have changed a lot of mod and scripts, so I am going to try it on vanilla E2E

**Comment by YiRanMushroom** [comment]
Still crashed
[crash-2023-02-12_23.37.37-client.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10716427/crash-2023-02-12_23.37.37-client.txt)

**Comment by YiRanMushroom** [comment]
I found it, it's toolprogression-1.12.2-1.6.12

**Comment by YiRanMushroom** [comment]
It seems that there are still other mods making this crash

**Comment by YiRanMushroom** [comment]
It could be phosphor-forge

**Comment by YiRanMushroom** [comment]
I am pretty sure that's the problem with these two mod.

**Comment by Alexsys** [comment]
I agree.

I'm using the latest RLCRAFT Test 666 patch,
and having this CORELIB crashes all the time.

without it, all is dandy


using the older version now, which doesnt cause the crash 1.0.19

**Comment by SuperMartijn642** [comment]
@Alexsys please create a separate issue with all the relevant information. You're updating from a way older version of my library, thus the issue is likely different.

**Comment by Alexsys** [comment]
> @Alexsys please create a separate issue with all the relevant information. You're updating from a way older version of my library, thus the issue is likely different.

I mean......
considering I'm using the same Forge, the same 1.12.2
and simply this older version plus older version of trashcan.

Unsure if it's any different.

I simply added the newest version of your Library, with the newest version of Trashcan, the LIB causes the crash,
all the same 1.12.2 stuff

I'll do so if I'll find a need to upgrade

**Comment by SuperMartijn642** [comment]
> It could be phosphor-forge

Ah yes, that's probably it then. I have had other people report issues with phosphor as well. Phosphor on Forge hasn't been supported in a while now and the source code for Phosphor for 1.12 is no longer available, thus sadly there's nothing I can do about it.

**Comment by navaroneee** [comment]
I've the same issue, but I dont use Phosphor
