### ISSUE TITLE
Exit code 0 after updating

### ISSUE THREAD

**Issue by Rokkhead** [SuperMartijn642/SuperMartijn642sCoreLib#2]
- supermartijn642corelib-1.0.15-mc1.12
- Minecraft 1.12.2

Hello,
just updated your corelib to 1.0.15, after that i get an exit code 0 crash, right after clicking start in the launcher. Rolling back to 1.0.14 fixed it. I dont get a crash report. I dont mind playing with an older version, i just wanted to inform you and maybe others have the same problem.

Have a nice day

**Comment by SuperMartijn642** [comment]
supermartijn642corelib-1.0.15-mc1.12 seems to be working fine for me.

Could you send me the `logs/latest.log` file?

**Comment by Rokkhead** [comment]
reinstalled the 1.0.15 and started again for latest log.

[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/7638893/latest.log)

**Comment by SuperMartijn642** [comment]
The crash only occurs when Malisis Core is installed. No clue why Malisis Core causes the core library to crash, however I did find a workaround which seems to do the trick.
It works together with Malisis Core now in version 1.0.15a for Minecraft 1.12.

Thank you for reporting the issue!

**Comment by Rokkhead** [comment]
Nice, you are welcome. Have a nice day.
