### ISSUE TITLE
[Crash] ...Crash on load with only this mod - java.lang.Exception: Mod Loading has failed

### ISSUE THREAD

**Issue by ProsperCraft** [SuperMartijn642/SuperMartijn642sCoreLib#21]
**Version Info**
- Minecraft, ...44.1.17   Minecraft 1.19.3
- Core Lib, ...supermartijn642corelib-1.1.3-forge-mc1.19.3.jar

**Steps to Reproduce**
...

**Crash report (~/logs/latest.log)**
...
https://gist.github.com/ProsperCraft/da15785649dbaeb85eec9c475c110139

**Comment by TYTheBeast** [comment]
Had the same issue on a larger custom modpack
https://crashy.net/c51b603a-23f2-45aa-98ab-58287d4e7d2b

**Comment by Peca21** [comment]
Same
https://mclo.gs/DVFtrdy
EDIT:
Looks like this is the problem
https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/commit/723b1604c1a4a0191605a66c6e3caa551272da33

**Comment by SuperMartijn642** [comment]
Fixed in version 1.1.4.
