### ISSUE TITLE
[Crash] Client refuses to launch after hitting play

### ISSUE THREAD

**Issue by coaber** [SuperMartijn642/SuperMartijn642sCoreLib#22]
**Version Info**
- Minecraft, 1.18.2
- Core Lib, 1.1.4
Client seems to stay open for a few seconds then shut down without any kind of error message from the launcher. opening the launcher just repeats the process, and sometimes it just stays open in the task manager idling and using some CPU.
**Steps to Reproduce**
...

**Crash report (~/logs/latest.log)**

[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10809017/latest.log)
[debug-1.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10809020/debug-1.log)

**Comment by SuperMartijn642** [comment]
My core library appears to launch fine on its own.

You seem to be using quite a lot of other mods. Could you confirm the issue is caused by my core library and if so, narrow down the mods needed to reproduce the issue?

**Comment by EVERETT-JOJO** [comment]
Same Issue Here
[crash-2023-02-22_18.30.12-fml.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10809584/crash-2023-02-22_18.30.12-fml.txt)
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/10809586/latest.log)

**Comment by EVERETT-JOJO** [comment]
I'm using my modpack (Everetts Forge v6.1) on curseforge

**Comment by SuperMartijn642** [comment]
@EVERETT-JOJO I don't see how that's even remotely the same as the issue above. Please update to version 1.1.4.

**Comment by coaber** [comment]
This has since been narrowed down to some FML incompatibilities, updating the Lib and it's dependents along with forge fixed the issue.
