### ISSUE TITLE
[Crash] Crash with RealBench

### ISSUE THREAD

**Issue by AzrielMud** [SuperMartijn642/SuperMartijn642sCoreLib#26]
**Version Info**
- Minecraft, 1.12.2
- Forge 14.23.5.2860
- Core Lib, 1.1.5

**Steps to Reproduce**
Starting game

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/11041795/latest.log)

**Comment by SuperMartijn642** [comment]
You are using a lot of mods. Please narrow down which other mods are needed to reproduce the issue.

**Comment by AzrielMud** [comment]
> You are using a lot of mods. Please narrow down which other mods are needed to reproduce the issue.

[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/11043126/latest.log)
That was RealBench 1.3.3
https://www.curseforge.com/minecraft/mc-mods/realbench/files

**Comment by SuperMartijn642** [comment]
Seems RealBench's source code is no longer available, so nothing I can do about it.
I can only suggest not using RealBench.
