### ISSUE TITLE
[1.12.2 Crash] Crash on the latest version of the Core Lib

### ISSUE THREAD

**Issue by vizthex123** [SuperMartijn642/SuperMartijn642sCoreLib#27]
**Version Info**
- Minecraft: 1.12.2
- Core Lib: 1.1.6

**Steps to Reproduce**
1) Install Core Lib v1.1.6 and PackedUp v1.0.28
2) Launch the game

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/11069679/latest.log)

Downgrading to Core Lib v1.0.19 and PackedUp v1.0.26 fixes the issue.

**Comment by SuperMartijn642** [comment]
Appears to be caused by Phosphor. Phosphor for Forge has been unsupported for years now and its source code is no longer available, so there's nothing I can do about it. Just don't use Phosphor.

If it is not Phosphor, please narrow the other mods needed to reproduce the issue and let me know.

**Comment by vizthex123** [comment]
Well, I figured I'd report it just in case.

I don't suppose you know of alternatives to Phosphor for 1.12.2?

**Comment by SuperMartijn642** [comment]
I do appreciate the report 🙂

> I don't suppose you know of alternatives to Phosphor for 1.12.2?

Nope sorry, I don't really play that much and especially not 1.12 😅

**Comment by vizthex123** [comment]
oof, worth a shot.
