### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by stivkis** [SuperMartijn642/SuperMartijn642sCoreLib#28]
**Version Info**
- Minecraft, 1.19.2
- Core Lib, 1.1.7

**Steps to Reproduce**
Sending a crash report for my friend, as he states - it happens by just launching the game while receiving the "java.lang.RuntimeException: null" message. I'm a newbie with MC crash logs, so I can't tell much about what happens.

[crash-2023-04-12_19.07.33-client.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/11214375/crash-2023-04-12_19.07.33-client.txt)

**Comment by SuperMartijn642** [comment]
![image](https://user-images.githubusercontent.com/12382965/231592618-ac3ad11a-5e99-422d-b86c-843f8eb85268.png)
![image](https://user-images.githubusercontent.com/12382965/231592705-8ae260d7-36e6-450e-bac3-77fbf54d60c5.png)
Those are the only errors shown in that log, so seems to be caused Create Crafts & Additions and Mystical Agriculture.
Anyways, nothing to do with my core library, so I'll close the issue.
