### ISSUE TITLE
[Bug] Installing the latest version of the mod on Fabric 1.19.2 makes it not launch due to 'Incompatible Mod Set'

### ISSUE THREAD

**Issue by IulianDan** [SuperMartijn642/SuperMartijn642sCoreLib#31]
**Version Info**
- Minecraft, 1.19.2 Fabric
- Core Lib, 1.1.7 for Fabric 1.19

**Description of the Bug**
Trying the latest and only available fabric version of the mod, it won't launch on 1.19.2

**Steps to Reproduce**
Install Mod on 1.19.2 with Fabric

**Screenshots**
![image](https://user-images.githubusercontent.com/32518786/236248178-c3f181a1-dacf-4b43-8b89-7d4233c08789.png)

**Comment by SuperMartijn642** [comment]
Like it says, my core library only support 1.19.4.

**Comment by IulianDan** [comment]
I see, sorry about that I guess.
I was trying a random asortment of mods for 1.19.2 and I thought trashcans needed it, but I couldn't find a 1.19.2 version of your corelib, so I just assumed the latest one supported all 1.19 versions.

**Comment by SuperMartijn642** [comment]
No worries 🙂 All my mods, including Trash Cans, are only available for 1.19.4 on Fabric.
