### ISSUE TITLE
[Crash] NPE on launch

### ISSUE THREAD

**Issue by andriihorpenko** [SuperMartijn642/SuperMartijn642sCoreLib#32]
**Version Info**
- Minecraft, 1.18.2
- Core Lib, 1.1.9

**Steps to Reproduce**
Just launch the game with the lib and [Masterful Machinery](https://github.com/ticticboooomer/MasterfulMachinery) (as it is mentioned in the stacktrace). It worked fine with version 1.1.7, but won't work on 1.1.9.

**Crash report (~/logs/latest.log)**
https://bytebin.lucko.me/zEAhq0Bcmf

**Comment by SuperMartijn642** [comment]
Masterful Machinery doesn't even start on its own it seems. If I install Masterful Machinery without any other mods, it just crashes on startup.
