### ISSUE TITLE
[Crash] crash after moving around in world a bit

### ISSUE THREAD

**Issue by Xplodin** [SuperMartijn642/SuperMartijn642sCoreLib#35]
**Version Info**
- Minecraft, 1.12.2
- Core Lib, 1.1.9b

**Steps to Reproduce**
create a world with this, thermal expansion, and aqua acrobatics, and a bunch of other mods
then move around a bit until game locks up.

Its hard to tell which is the cause to be honest.
**Crash report (~/logs/latest.log)**
[...](https://gist.github.com/Xplodin/c54deffce4ff71105c4d8e7957184a56)

**Comment by SuperMartijn642** [comment]
Appears to have nothing to do with my core library.

It seems to be caused by Thermal Expansion or CoFH Core
![image](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/assets/12382965/3450abc3-b7f9-4ed0-8e47-4c7ff813a018)

**Comment by Xplodin** [comment]
sorry for the issue, it was mixinbooter.
