### ISSUE TITLE
[Crash] CoreLib crashes when added to Divine Journey 2 modpack

### ISSUE THREAD

**Issue by BiggerGreen** [SuperMartijn642/SuperMartijn642sCoreLib#38]
**Version Info**
- Minecraft, 1.12.2
- Core Lib, 1.1.10, tries upgrading to 1.1.11, didn't fix the issue.

**Steps to Reproduce**
Just try to boot the game.

**Crash report (~/logs/latest.log)**
https://pastebin.com/6Zvh5dCt

This is a crash I'm getting while trying to add the Tesseract mod to the Divine Journey 2 modpack. I've boiled it down to being CoreLib, as opposed to ConfigLib or the Tesseract mod itself.

**Comment by SuperMartijn642** [comment]
Caused by Phosphor. Phosphor on Forge has been abandoned for years now and its source code is no longer available, so there's not much I can do about it.
Just don't use Phosphor.

**Comment by BiggerGreen** [comment]
Got it! Thanks for the help.
