### ISSUE TITLE
Crashing on start up out of nowhere.[Crash] ...

### ISSUE THREAD

**Issue by Amdar210** [SuperMartijn642/SuperMartijn642sCoreLib#39]
**Version Info**
- Minecraft, ... 1.19.2
- Core Lib, ... 1.1.12-forge-mc1.19.2.jar

**Steps to Reproduce**
...Load up Minecraft via Curseforge launcher with mods. Results in the smaller launcher/minecraft game window to appear for a few seconds before crashing.

**Crash report (~/logs/latest.log)**
...
[crash-2023-07-26_20.15.01-client.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/12178751/crash-2023-07-26_20.15.01-client.txt)

**Comment by SuperMartijn642** [comment]
As far as I can tell, nothing in that log has anything to do with my core library 🤔

The only mods mentioned in the error are CoFH Core and ModernFix.
