### ISSUE TITLE
[Crash] Optifine

### ISSUE THREAD

**Issue by Sephiroth91** [SuperMartijn642/SuperMartijn642sCoreLib#4]
**Version Info**
- Minecraft, 1.12.2, Forge 2855
- Core Lib: 1.0.15a

If I take Optifine in the mod folder, minecraft is crashing while loading. If there is no Optifine in the mod folder it works well.

**Crash report (~/logs/latest.log)**
...
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/7678507/latest.log)

**Comment by SuperMartijn642** [comment]
OptiFine changes a lot about Minecraft's rendering, however, it is also closed source, thus there's no way for others to know what it changes.
I will look into it, but there's likely nothing I can do about it.

**Comment by Scheigster** [comment]
I'm having the same issue with 1.0.15a. At first, I thought it was linked to the MalisisCore issue that is closed but it actually seems to be Optifine.

The version 1.0.14 doesn't have that issue, which might help you pinpoint the problem.

**Comment by Sephiroth91** [comment]
I can confirm that. I have tested it. With version 1.0.14 all works

**Comment by SuperMartijn642** [comment]
Yes, in 1.0.15 I added a mixin for a Minecraft method `EntityRenderer#renderWorldPass`. Apparently, OptiFine completely changes that method, however I have no way to know what it looks like after OptiFine changed it as OptiFine is closed source.

**Comment by Scheigster** [comment]
I understand. Maybe put a warning somewhere that your lib latest version won't be able to run on modpacks running Optifine ?

**Comment by LoneWolfGmer** [comment]
this does indeed seem to be an issue I myself spent 4 hours trying to fix after updating my copy of this very mod from 11/13/2021
supermartijn642corelib-1.0.14-mc1.12.jar
Release
1.12.2

to the latest also. yes using optifine was likely the issue. but I need my dynamic lightings

a warning about this issue would be useful though for sure

**Comment by LoneWolfGmer** [comment]
> **Version Info**
> 
>     * Minecraft, 1.12.2, Forge 2855
> 
>     * Core Lib: 1.0.15a
> 
> 
> If I take Optifine in the mod folder, minecraft is crashing while loading. If there is no Optifine in the mod folder it works well.
> 
> **Crash report (~/logs/latest.log)** ... [latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/7678507/latest.log)

also a note on this. my copy doesn't even run it just gets stuck in a  loop. being between running and not in a crashed but running state.

going back to 
supermartijn642corelib-1.0.14-mc1.12.jar

seemed to be a fix though for me. and those who want to use optifine

**Comment by MrRedstoneA1** [comment]
Also had this issue. Thought it was a mod incompatibility but then tried in a clean install, only to find that it still crashes with the only other mod being Optifine. I keep a clean testing install that only has Optifine for compatibility reasons (say, if a mod isn't happy with some Optifine setting I could report it to the dev)

**Comment by SuperMartijn642** [comment]
Core library version 1.0.16a will now work with OptiFine again on Minecraft 1.12.

Thank you all for reporting the issue.
