### ISSUE TITLE
[Crash] Registry changes can cause structures to start registering before block id's exist

### ISSUE THREAD

**Issue by NighthowlerStudios** [SuperMartijn642/SuperMartijn642sCoreLib#40]
**Version Info**
- Minecraft, 1.16.5
- Core Lib, 1.1.0+

**Steps to Reproduce**
This crash is extraordinarily rare due to thread racing, however it has happened to my modpack multiple times now.  your mod does not appear in the pathtrace but I feel that the way your mod changes the pipeline of registry may be at fault.  I have talked to the modders of these structure mods already and they had no clue what would cause this.

It can happen on Kaleidio's Battle Pack 5.3.4, by creating a new world and it will crash before the "loading terrain" stage, where chunks should have their initial generation happening.  note due to the rarity, it may take near 100 attempts or lower end/higher end hardware to trigger

All structure mods involved will claim a block id is missing the moment it attempts to place a feature, which can happen anywhere from the air block all the way to some other mod's block.  I have tried to directly trace this error before but I could not see any reason.  Then I started looking towards what each core mod has the capability of doing, and spotted your registry changes and subsequent bugs since 1.1.0, and I have a feeling it is related.

**Crash report (~/logs/latest.log)**
[crash-2023-07-07_15.24.33-server.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/12260836/crash-2023-07-07_15.24.33-server.txt)

**Comment by SuperMartijn642** [comment]
> that the way your mod changes the pipeline of registry may be at fault

Wut, my core library does not change anything about the registry pipeline 🤔

**Comment by NighthowlerStudios** [comment]
alright.  I have been working on a hunch for ages, guess my hope is lost again.  I'll try researching this more...
