### ISSUE TITLE
Game Crashes on start Minecraft 1.12.2  modpacks:Divine Journey 2 :2.19.3

### ISSUE THREAD

**Issue by SenjumaruShutara** [SuperMartijn642/SuperMartijn642sCoreLib#42]
**Version Info**
- Minecraft:1.12.2,Forge :14.23.5.2860
-modpacks:Divine Journey 2 :2.19.3
SuperMartijn642sCoreLib:1.1.10-1.1.12
[crash-2023-08-05_10.58.10-client.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/12265987/crash-2023-08-05_10.58.10-client.txt)

**Comment by SuperMartijn642** [comment]
VanillaFix, Phosphor and Tool Progression conflict with my core library.

**Comment by SenjumaruShutara** [comment]
> VanillaFix, Phosphor and Tool Progression conflict with my core library.

Oh, I see.  Thank you
