### ISSUE TITLE
[Feature] Marking Core Lib as Quilt compatbile on Modrinth

### ISSUE THREAD

**Issue by GitUser14975** [SuperMartijn642/SuperMartijn642sCoreLib#46]
Hey, so some of your mods like Additional Lanterns are marked as quilt compatbile and i can add them to my modrinth modpack with no problem. However they all require the core lib, which isn't marked as quilt compatbile and I can't add it to the modpack. Could that be changed?

**Comment by SuperMartijn642** [comment]
Welp after about 2 hours of marking files, the latest versions of my mods for each Minecraft version are now marked with NeoForge is they were Forge and with Quilt if they were Fabric.
To be honest, I didn't even realize Fabric mods not explicitly marked with Quilt, could not be included in Quilt packs.
