### ISSUE TITLE
Weird crash that needs to be addressed

### ISSUE THREAD

**Issue by Sunconure11** [SuperMartijn642/SuperMartijn642sCoreLib#47]
https://pastebin.com/vzxC3xTN

**Comment by SuperMartijn642** [comment]
Nothing to do with my core library, caused by whichever mod adds `io.ejekta.kambrik.logging.KambrikMarkers.createIdMarker(KambrikMarkers.kt:16)`. Their mixin just happens to be applied when my core library loads the class they mixin to.

Also, fill in the template. It's there for a reason.
