### ISSUE TITLE
[Question] How come this mod doesn't work with Quilt even though on Modrith it does?

### ISSUE THREAD

**Issue by Aqua-neko-ow** [SuperMartijn642/SuperMartijn642sCoreLib#48]
**Question**
When I use this mode with Quilt it says Illegal access to quilt loader

**Comment by SuperMartijn642** [comment]
Please use the correct template.

What version of my core library are you using? What version of Minecraft are you using? What version of Quilt Loader are you using? Please share the logs.

**Comment by Aqua-neko-ow** [comment]
Sorry I'm used to templates on GitHub but it was 1.1.12a I believe Minecraft version: 1.19.2 quilt: 0.20.2. Yeah I don't have any log file because I deleted that instance I'm sorry but I can recreate it right now

**Comment by Aqua-neko-ow** [comment]
"[20:39:07] [main/INFO]: I used the json to destroy the json
[20:39:09] [main/WARN]: Found illegal access from SuperMartijn642's Core Lib to Quilt Loader
 class com/supermartijn642/core/CoreLib.onPreLaunch()V
 accessed the field org/quiltmc/loader/impl/QuiltLoaderImpl.INSTANCE
Please don't use this, instead try using the public api class org.quiltmc.loader.api.QuiltLoader - that way you can have guaranteed backwards compatibility!
[20:39:09] [main/WARN]: Found illegal access from SuperMartijn642's Core Lib to Quilt Loader
 class com/supermartijn642/core/CoreLib.onPreLaunch()V
 accessed the field org/quiltmc/loader/impl/util/DefaultLanguageAdapter.INSTANCE
Please don't use this, instead ask Quilt Loader to declare a new public API that can have guarenteed backwards compatibility!"
This is all it says when it does say that.

**Comment by SuperMartijn642** [comment]
But those are just warnings. How does that make it 'not work with Quilt'?

**Comment by Aqua-neko-ow** [comment]
Personally I don't really know because I don't do Minecraft modding often I mainly do Kingdom Hearts modding. So I thought that it was saying that this mod isn't going to work.

**Comment by SuperMartijn642** [comment]
The mod works just fine on Quilt.
