### ISSUE TITLE
[Question] Why won't my mods work?

### ISSUE THREAD

**Issue by Jrockcreeper** [SuperMartijn642/SuperMartijn642sCoreLib#5]
**Question**
I downloaded your chunk loader mod and opened Minecraft it said I needed supermartijn642corelib 1.0.15 so I downloaded that too. But its still asking me for this supermartijn642 1.0.9. I'm not sure if this is just an issue for 1.18.1 Minecraft or I'm still missing something.

**Comment by SuperMartijn642** [comment]
I have a core and a config library. It is probably asking you for the config library. https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib

Btw, CurseForge will show you the dependencies if you click on the file you want to use.
![Screenshot_20220108-124548](https://user-images.githubusercontent.com/12382965/148642935-3492e9fd-edc0-4e58-a5f0-663bf8a7a117.png)

**Comment by Jrockcreeper** [comment]
> I have a core and a config library. It is probably asking you for the config library. https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib
> 
> Btw, CurseForge will show you the dependencies if you click on the file you want to use. ![Screenshot_20220108-124548](https://user-images.githubusercontent.com/12382965/148642935-3492e9fd-edc0-4e58-a5f0-663bf8a7a117.png)
