### ISSUE TITLE
[Crash] Creative Tab crash game

### ISSUE THREAD

**Issue by iGorTha** [SuperMartijn642/SuperMartijn642sCoreLib#53]
**Version Info** 
- Minecraft, 1.12.2
- Core Lib, 1.1.12

**Steps to Reproduce**
- Joining a server without the "MovingElevator" server mods
- Open creative tab 
- Switch page 
- Crash game ....

**Crash report (~/logs/latest.log)**
[crash-2023-10-23_18.02.43-client.txt](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/13073648/crash-2023-10-23_18.02.43-client.txt)

**Comment by SuperMartijn642** [comment]
Moving Elevators is required on both the server and the client. You should not be able to join a server **without** Moving Elevators with a client **with** Moving Elevators.
If you can, that is likely caused by some other mod you have installed.

**Comment by iGorTha** [comment]
Okay, I've got two servers 1 with the mod and the other without.
Thanks just the same, I'll install it on both servers.
