### ISSUE TITLE
[Crash] client crash

### ISSUE THREAD

**Issue by mlbhc** [SuperMartijn642/SuperMartijn642sCoreLib#55]
**Version Info**
- Minecraft, 1.20.1
- Core Lib, supermartijn642corelib-1.1.12a-forge-mc1.20

**Steps to Reproduce**
When I turn on shader to join my server,the client crashed.If turn off shader, this problem will not appear.

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/13420916/latest.log)

**Comment by SuperMartijn642** [comment]
This is a crash between Moving Elevators and OptiFine. OptiFine is closed source so nothing I can do about it.
You can use better alternatives like Iris or Oculus.
