### ISSUE TITLE
[Bug] Minecraft doesnt open with it in Forge.

### ISSUE THREAD

**Issue by Moyplayer123** [SuperMartijn642/SuperMartijn642sCoreLib#59]
When I try and open it it says requires 'supermartijn642configlib 1.1.6 or above' when I have already downloaded 'supermartijn642corelib-1.1.7-forge-mc1.19.4'.

![image](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/assets/157917318/34501b6f-0707-4e22-95fb-4c0ae565d783)

**Comment by SuperMartijn642** [comment]
That is asking for my config library, not core library.
![image](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/assets/12382965/132be3f2-5aea-4b26-b42a-4538ad1dc4d3)

**Comment by Moyplayer123** [comment]
Thank you for helping me as I didnt realise that you had to download both. Btw the mod is awesome.
