### ISSUE TITLE
[Crash] crashes with latest forge version

### ISSUE THREAD

**Issue by QuibopWon** [SuperMartijn642/SuperMartijn642sCoreLib#6]
- latest version of core lib
- Minecraft 1.18.1 forge 39.0.50
- Core Lib, other mods are listed in the crash report i think

**Steps to Reproduce**
step 1: put corelib into the latest release of 1.18.1 forge
step 2: start it up
step 3: crash

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/7908562/latest.log)

**Comment by SuperMartijn642** [comment]
This is an issue in Forge 39.0.49 and up and has nothing to do with my core library.
For now, you can downgrade to Forge 39.0.48 until Forge fixes the issue.

> latest version of core lib

As a side note, please note the actual version instead of 'latest'

**Comment by SuperMartijn642** [comment]
FYI Forge 39.0.54 now fixes the crash introduced in 39.0.49.

**Comment by QuibopWon** [comment]
aight, thanks for telling me

**Comment by Hydraheads** [comment]
Broken with more recent forges again.
No offense, but I'd rather not update this mod than lose the security and bug fixes that the forge dev team worked on, can you consider making it compatible with current forge 1.12?

**Comment by SuperMartijn642** [comment]
My core library works just fine with the latest version of Forge for 1.12.
This issue is about a bug in certain Forge versions for 1.18.1 and has nothing to do with 1.12.

Please open a new issue with version info and logs if you're experiencing issues.
