### ISSUE TITLE
[Bug] 1.20.6 is not allowed

### ISSUE THREAD

**Issue by PukPukov** [SuperMartijn642/SuperMartijn642sCoreLib#60]
1.20.5 mods are compatible with 1.20.6, but mod does not allow loading on 1.20.6

**Comment by SuperMartijn642** [comment]
My core library does not work on 1.20.5 nor 1.20.6 🤔

**Comment by PukPukov** [comment]
Oops, "1.20.5 (exclusive)" in fabric confused me.
