### ISSUE TITLE
[Bug] Recipes not show up in JEI. MC 1.21 Fabric Server

### ISSUE THREAD

**Issue by Knito58** [SuperMartijn642/SuperMartijn642sCoreLib#62]
**Version Info**
- Minecraft, 1.21 Fabric loader 0.15.11
- Core Lib, 1.1.17

**Description of the Bug**
The blocks and items of mod "moving elevater" and "packed up" show up in JEI.
When clicking for the recipes there's nothing. 
The recipes do NOT show up.

**Steps to Reproduce**
Playing on Fabric server. Having Super mods installed.

**Screenshots**
![2024-07-22_12 50 21](https://github.com/user-attachments/assets/b8fbee78-1cde-4617-829b-ae6e7e750a08)

**Comment by SuperMartijn642** [comment]
Do the recipes actually work?

**Comment by Knito58** [comment]
I don't know as I don't see them. I just looked in some other 1.21 single player worlds but the super mods were not there. Can you screenshot me a recipe to test it - packed up or moving elevators?

**Comment by SuperMartijn642** [comment]
The recipes are shown on the mod page. I am currently on my phone so a bit hard to get it for you 😅

If the recipes do work but JEI doesn't show them, then it is likely a bug with JEI.

**Comment by Knito58** [comment]
![2024-07-22_152019](https://github.com/user-attachments/assets/ca8f37d1-c0cd-4749-a494-8b1afef22441)
I tried with the standard backpack recipe from the modpage. The crafting result slot stays empty.

**Comment by SuperMartijn642** [comment]
Then it'd be just the recipes not working rather than something to do with JEI.
Did you install the mods on the server? You can check by using the `/give @p packedup:basicbackpack` command to see if the item exists.

**Comment by Knito58** [comment]
Result: Unknown Item "packedup:basicbackpack"

**Comment by Knito58** [comment]
I'm very certain that JEI still needs some honing as it tooltips every item as made of 6 components. But it works with very many recipes, even with other modded recipes.

**Comment by SuperMartijn642** [comment]
> Result: Unknown Item "packedup:basicbackpack"

That'd mean the mod is not loaded on the server.

> as it tooltips every item as made of 6 components.

I believe that's a vanilla thing if you press F3+H, not JEI.

**Comment by Knito58** [comment]
Ok if the mod was not loaded then I should not see the mod's items in JEI, am I right?

**Comment by SuperMartijn642** [comment]
You will still see the mod's items in JEI as item registration is done client-side. Recipes are synced from the server to the client hence those won't show up.

**Comment by Knito58** [comment]
I see. Checking files and logs on server.

**Comment by Knito58** [comment]
Thank you very much for your help! You were right. It was all my fault(s). Sorry for disturbing you.
Filezilla did upload a lot but not update the server files in the mod folder.
Probably me dumbfingering.
