### ISSUE TITLE
All mod with this library[Crash] ...

### ISSUE THREAD

**Issue by Arch23-tech** [SuperMartijn642/SuperMartijn642sCoreLib#63]
For unknown reason whenever I use one of these mods ( entangled, moving elevator) my game crashs after a few minutes of gameplay when I come close around entities and mobs .

Optifine + 1.20.1

**Comment by SuperMartijn642** [comment]
Please fill in the template. I can't do anything without any info. I don't even know which Minecraft version or modloader you are using.
