### ISSUE TITLE
[Crash] mod injection failed.

### ISSUE THREAD

**Issue by al-wei** [SuperMartijn642/SuperMartijn642sCoreLib#64]
**Version Info**
- Minecraft, 1.12.2
- Core Lib, _supermartijn642corelib-1.1.17-forge-mc1.12

**Steps to Reproduce**
mod injection failed.

**Crash report (~/logs/latest.log)**

https://mclo.gs/hLjOMBE

**Comment by SuperMartijn642** [comment]
This is caused by a mixin from some other mod you have. Likely something related to `meldexun.renderlib.asm.RenderLibClassTransformer@3e4ead73 from coremod RenderLibPlugin`.

**Comment by al-wei** [comment]
renderlib
