### ISSUE TITLE
[Bug]Unable to join the world when the server has been running for a while

### ISSUE THREAD

**Issue by ZHENGLOC** [SuperMartijn642/SuperMartijn642sCoreLib#66]
**Version Info**
- Minecraft 1.21
- NeoForge 21.0.151
- Core Lib 1.1.17c-neoforge
- Config Lib 1.1.8-neoforge

**Description of the Bug**
As the screenshot shows, the server will suddenly fail to join after running for a while.
I'm not sure if this is an issue with the supermartijn642 core/config lib, but the game points to a directory (.minecraft/debug) after being unable to join the world.
The files in the directory are suspected to point to it being a problem with this mod.
(Just like #65 ?)

This is the file in the debug folder:
 My: [disconnect-2024-08-07_21.34.35-client.txt](https://github.com/user-attachments/files/16530824/disconnect-2024-08-07_21.34.35-client.txt)
My friend: [disconnect-2024-08-07_23.08.13-client.txt](https://github.com/user-attachments/files/16530828/disconnect-2024-08-07_23.08.13-client.txt)
This is the server log file: [2024-08-07-6.log](https://github.com/user-attachments/files/16530837/2024-08-07-6.log)

**Steps to Reproduce**
I don't know how to reproduce this bug as it appears for no reason.

（DeepL machine translation）
**Screenshots**
![2D8E43D0D505DA788AA06A1B9D3D088A](https://github.com/user-attachments/assets/064934f2-e860-4080-b64b-a4c4675220a4)

**Comment by SuperMartijn642** [comment]
This was an issue with Entangled (https://github.com/SuperMartijn642/Entangled/issues/89) and should be fixed now in Entangled version 1.3.18a.
Thank you for reporting the issue!
