### ISSUE TITLE
Collapse often sees your mod name

### ISSUE THREAD

**Issue by zc1108aaa** [SuperMartijn642/SuperMartijn642sCoreLib#68]
[crash-2024-09-06_18.01.22-client.txt](https://github.com/user-attachments/files/16906238/crash-2024-09-06_18.01.22-client.txt)

**Comment by SuperMartijn642** [comment]
Please fill in the template, it's there for a reason.
That crash has nothing to do with my core library. It is caused by a mods which adds a mixin for the `MinecraftClient` class. My core library just happens to be the first to load that class.
