### ISSUE TITLE
[Crash][1.12.2] Crash with GregTech CE: Unofficial

### ISSUE THREAD

**Issue by accessdenied0** [SuperMartijn642/SuperMartijn642sCoreLib#7]
**Version Info**
- Minecraft, 1.12.2
- Core Lib, 1.0.16a-mc1.12
- Forge 14.23.5.2860

**Steps to Reproduce**

Unsure:
Install both mods required for/and Rechiseled

...

**[crashreport](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/7917346/crash-2022-01-22_02.06.00-client.txt)**
...

I'm sorry for the lack of information, I'm myself a bit riddled by this one. I'm also aware that this is a very old version now and I am sorry to bring up this issue, still. I can't rule out, it might be an issue from a different mod, but I am unsure where to search.
Crash happens soon the Game starts (Window just opened)

**Comment by SuperMartijn642** [comment]
After some testing, it appears it crashes specifically when GregTech CE: Unofficial is installed.

**Comment by accessdenied0** [comment]
Ohh I thank you for your effort! 
Sorry for the extra work...

This is really unfortunate... I linked the corresponding issue over there.

**Comment by SuperMartijn642** [comment]
It should now work with my core library version 1.0.16b for 1.12.
