### ISSUE TITLE
[Crash] "exception ticking world"

### ISSUE THREAD

**Issue by nikolodeon** [SuperMartijn642/SuperMartijn642sCoreLib#8]
**Forge-39.0.59**
- Minecraft, 1.18.1
- Core Lib, -1.0.16a-mc1.18.jar

**whenever i try loading into my game. It gets to a certain percentage (usually 100) on the loading screen and then it crashes. This only happens when i join a specific world that i made. when joining other worlds, this doesn't happen**
...

**Crash report:
[latest.log](https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/files/7927284/latest.log)

...

**Comment by SuperMartijn642** [comment]
This is caused by BetterFurnacesReforged and has nothing to do with my core library.

**Comment by nikolodeon** [comment]
oh i'm sorry for wrongly reading the crash report! thanks for the info!

**Comment by SuperMartijn642** [comment]
No worries 🙂
