### ISSUE TITLE
[Crash] crash when install with Optifine

### ISSUE THREAD

**Issue by TUsama** [SuperMartijn642/SuperMartijn642sCoreLib#9]
**Version Info**
- Minecraft, 1.12.2   Forge 14.23.5.2860
- Core Lib, 1.0.9a-mc1.12

**Steps to Reproduce**
1. install [preview_OptiFine_1.12.2_HD_U_G6_pre1.jar](http://adfoc.us/serve/sitelinks/?id=475250&url=http://optifine.net/adloadx?f=preview_OptiFine_1.12.2_HD_U_G6_pre1.jar&x=cb0e)
2. install supermartijn642configlib-1.0.9a-mc1.12.jar, supermartijn642corelib-1.0.16-mc1.12.jar, movingelevators-1.3.5-mc1.12.jar
3. start  the game

**Crash report**

[latest.log](https://paste.ee/p/JcEOO)

**Comment by SuperMartijn642** [comment]
Should work now with my core library version 1.0.16b for 1.12.

**Comment by TUsama** [comment]
Thank you so much.
